### PR TITLE
update to version 3

### PR DESCRIPTION
**Pull request by edewit**
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Comment by edewit** [comment]
Ahh yes this text need to be changed as hidden is no longer a thing

**Comment by edewit** [comment]
fixed the JSX screen:
image

**Comment by hmlnarik** [comment]
@edewit The fix for the tests is available in https://github.com/edewit/keycloak-quickstarts/pull/1.

There is the last test missing - that is for JSX which seem not to work for me yet, I still got the "Something went wrong" message. Is the `maven clean install -Dextension` sufficient?

Please update the target for this PR into `main` quickstarts branch. The difference between the branches got lost with the latest rewrite of the CONTRIBUTING, so the reference in [its older version](https://github.com/keycloak/keycloak-quickstarts/blob/21.1.2/CONTRIBUTING.md#picking-correct-branch-for-your-pr). This will be fixed in a separate PR.

**Review by hmlnarik — APPROVED** [review]
LGTM, thanks. The failed tests are unrelated to this PR, and the test for this extension correctly passes:

```
[INFO] Reactor Summary for Keycloak Quickstart: parent 999.0.0-SNAPSHOT:
[INFO] 
[INFO] Keycloak Quickstart: parent ........................ SUCCESS [  0.103 s]
[INFO] Quickstart: Action Token With Authenticator ........ SUCCESS [ 29.638 s]
[INFO] Quickstart: Action Token With Required Action ...... SUCCESS [  0.592 s]
[INFO] Keycloak Quickstart: Event Listener System.out ..... SUCCESS [  0.527 s]
[INFO] Keycloak Quickstart: Event Store In-Mem ............ SUCCESS [  0.437 s]
[INFO] Keycloak Quickstarts: Extend Account Console ....... SUCCESS [  5.520 s]
[INFO] Keycloak Quickstart: user-storage-properties ....... FAILURE [  0.181 s]
[INFO] Keycloak Quickstart: user-storage-jpa .............. SKIPPED
```

**Comment by antoine-roux** [comment]
Hello,
Since the version 3, it is no longer possible to access to the KeycloakContext, and the widget library like before.
Transpiled .js files obviously have unpredictable names...

Before, I used:
```python
import { AccountServiceContext } from "../../account-service/AccountServiceContext.js";
import { Msg } from "../../widgets/Msg.js";
```

Do you have a solution for this kind of thing?

Antoine

**Comment by edewit** [comment]
@antoine-roux right we now use a bundler, so this is indeed no longer possible. But we will have an library where you can build your own console and reuse the pages from the account

**Comment by antoine-roux** [comment]
@edewit by any chance, do you know if there's any news about this? Version 2 has now been removed from Keycloak, it's a blocking issue now.

**Pull request merged**
