### PR TITLE
Update apiVersion to networking.k8s.io/v1 as extensions/v1beta1 has b…

### PR DESCRIPTION
**Pull request by Tin-Nguyen**
Updating apiVersion to networking.k8s.io/v1 in keycloak-ingress.yaml as extensions/v1beta1 has been deprecated in 1.20v

### CODE REVIEW

**Comment by Tin-Nguyen** [comment]
Hi @team, anyone help to review the change? would like to save a bit time for the community

**Review by vmuzikar — COMMENTED** [review]
@Tin-Nguyen Thank you for your contribution! Could you please create a JIRA for this and add its ID to the commit message? Also, could you squash the commits?

@slaskawi I think this change should be done also at the Operator side as well, right? AFAICT, we [use old API](https://github.com/keycloak/keycloak-operator/blob/410337e825ccc6668932d8dc31826d5bcad792a2/pkg/model/keycloak_ingress.go#L5) there too.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
One last thing. This change needs to go to `master` branch, not `latest`.

**Comment by vmuzikar** [comment]
@abstractj Can you please close this. It needs to go to a different branch.

**Comment by slaskawi** [comment]
+1 - please merge it against the master branch. But the change LGTM.

**Pull request closed without merging**
