### PR TITLE
Fix connection error in service-nodejs test 

### PR DESCRIPTION
**Pull request by tkyjovsk**
Attempt to fix connection error in `service-nodejs` test - #381 . Also includes recent commit from Ivan to fix app-springboot - #378 .

### CODE REVIEW

**Review by vmuzikar — APPROVED** [review]

**Review by vmuzikar — CHANGES_REQUESTED** [review]
Actually, shouldn't this target `main` instead of `latest`?

**Comment by tkyjovsk** [comment]
@vmuzikar Hm, I think you're right. The scheduled QS test workflow run against the main.
```
jobs:
  tests:
    name: Quickstarts tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: ${{ github.event_name != 'schedule' }}
      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'schedule' }}
        with:
          ref: 'main'
```

**Comment by tkyjovsk** [comment]
Should I close this one and create new PR for `main`?

**Comment by vmuzikar** [comment]
@tkyjovsk I tried to change the base branch but there are conflicts now. Can you please fix them?

**Comment by vmuzikar** [comment]
BTW, definitely should go to `main`. 🙂 See: https://github.com/keycloak/keycloak-quickstarts/blob/06db58ad5748c874f808419582382d8b829dcdfa/CONTRIBUTING.md?plain=1#L74-L78

**Review by vmuzikar — APPROVED** [review]

**Pull request merged**
