### PR TITLE
[KEYCLOAK-4869] Integration tests for app-html5 are failing after upgrade to 3.1.0.Final

### PR DESCRIPTION
**Pull request by abstractj**
- Moves package page to keycloak-test-helper. We had a lot of duplicated
code
- Fixes the issue with HTML5 app
- Travis script to build the quickstarts based on branches

This PR add the builds based on the development version of Keycloak for the branch `master` only. It should not affect the latest.

#### Important consideration about this PR:
* https://github.com/keycloak/keycloak/pull/4176 must be **merged** first
* This line https://github.com/keycloak/keycloak-quickstarts/compare/latest...abstractj:KEYCLOAK-4869?expand=1#diff-f9a62833538ab14fff849c2be16ab986R3 must change to keycloak repository after we agree on this change.

### CODE REVIEW

**Comment by sebastienblanc** [comment]
@abstractj https://github.com/keycloak/keycloak/pull/4176 has been merged , not sure about the line you mention that needs to be changed https://github.com/keycloak/keycloak-quickstarts/compare/latest...abstractj:KEYCLOAK-4869?expand=1#diff-f9a62833538ab14fff849c2be16ab986R3 , looks like already correct, isn't it ?

**Comment by abstractj** [comment]
@sebastienblanc I just rebased and updated. the script. Now it points to keycloak on master.

**Comment by sebastienblanc** [comment]
Landed on `master`

**Comment by abstractj** [comment]
@sebastienblanc thank you!

**Pull request closed without merging**
