### PR TITLE
update to use the new flags

### PR DESCRIPTION
**Pull request by edewit**
fixes: https://github.com/keycloak/keycloak/issues/34040
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

**Comment by mposolda** [comment]
@edewit Is it possible to send the PR to `main` instead? The branch `latest` is not supposed for new PRs as it is always replaced by the `main` branch during each release.

**Comment by edewit** [comment]
@mposolda yes, sorry I keep forgetting

**Comment by mposolda** [comment]
@edewit Thanks, is it possible to remove all the version changes of `pom.xml` files from this PR?

**Comment by edewit** [comment]
strange a bot did that @mposolda, but done

**Review by mposolda — APPROVED** [review]
@edewit Thanks!

**Pull request merged**
