### PR TITLE
Migrate to adapter-elytron-install-offline.cli to avoid exception "Legacy WildFly security layer..."

### LINKED ISSUE #325: On main, several examples fail with "Legacy WildFly security layer is no longer supported"
### Describe the bug

When running the quickstart compile action on the main Keycloak repository, the quickstarts fail with the following message: 

> Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter

```
$ grep -E '(Z Caused by:.*Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter|Running tests for)' qs1.txt
Running tests for action-token-authenticator QS
Running tests for action-token-required-action QS
Running tests for app-authz-rest-springboot QS
Running tests for app-authz-spring-security QS
Running tests for app-authz-springboot QS
Running tests for app-authz-springboot-multitenancy QS
Running tests for app-authz-jee-servlet QS
Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
Running tests for app-authz-jee-vanilla QS
Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
Running tests for app-authz-photoz QS
Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
Running tests for app-authz-rest-employee QS
Running tests for app-authz-uma-photoz QS
Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
Running tests for app-jee-html5 QS
Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
Running tests for app-jee-jsp QS
Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
Running tests for app-profile-jee-html5 QS
Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
Running tests for app-profile-jee-jsp QS
Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
Running tests for app-profile-jee-vanilla QS
Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
Running tests for app-profile-saml-jee-jsp QS
Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
Running tests for event-listener-sysout QS
Running tests for event-store-mem QS
Running tests for extend-account-console QS
Running tests for service-jee-jaxrs QS
Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
Running tests for service-springboot-rest QS
Running tests for user-storage-jpa-legacy QS
Running tests for user-storage-simple QS
Running tests for app-springboot QS
```

### Version

999-SNAPSHOT

### PR DESCRIPTION
**Pull request by ahus1**
…is no longer supported by the Keycloak WildFly adapter"

Closes #325

### CODE REVIEW

**Comment by ahus1** [comment]
Due to [#keycloak/11789](https://github.com/keycloak/keycloak/pull/11789) several of the examples fail with "Legacy WildFly security layer is no longer supported""

This PR disables those from the CI run in `main` as a minimal change. 

As you've been involved in the original issue @stianst / @pedroigor / @abstractj:
Should those quickstarts be removed completely from this repository? 

BTW; other quickstarts will fail for other reasons.

**Review by vmuzikar — COMMENTED** [review]
@ahus1 Thanks for the PR!

Maybe we could rather migrate the QS to Quarkus instead of removing them completely?

**Comment by ahus1** [comment]
@vmuzikar - true, they might be migrated, but that would be another issue and out of scope for this PR. I don't have a strong opinion here, so I won't open such an issue.

**Review by pedroigor — COMMENTED** [review]
@ahus1 As mentioned by @abstractj , removing is not really the solution.

Instead we should change the quickstarts to use the Elytron Adapter instead of the legacy one.

For that, we should be able to solve this specific problem by changing this line https://github.com/keycloak/keycloak-quickstarts/blob/00224ca98d39c52833c3fc6e80aa25a63a8ff91b/pom.xml#L440.

And run the `adapter-elytron-install-offline.cli` script instead. That should enable Elytron to the undertow subsystem and avoid the error:

```
Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
```

**Comment by pedroigor** [comment]
@ahus1 IMO, we should remove `app-profile-jee-vanilla` because it teaches how to use the legacy adapter and subsystem that no longer exists.

The SAML one I need to take a look at because I think it should work just fine as we are not removing SAML.

**Comment by hmlnarik** [comment]
> Any idea why this is still the case? Or should this PR be merged, and the other failures should be tackled in another PR?

Could it be because of the https://github.com/keycloak/keycloak-quickstarts/blob/latest/app-profile-jee-vanilla/src/test/resources/standalone-test.xml containing references to legacy security subsystems?

https://github.com/keycloak/keycloak-quickstarts/blob/8129f103f7304497884fa9314f3db4d4d8b7695a/app-profile-jee-vanilla/src/test/resources/standalone-test.xml#L22

https://github.com/keycloak/keycloak-quickstarts/blob/8129f103f7304497884fa9314f3db4d4d8b7695a/app-profile-jee-vanilla/src/test/resources/standalone-test.xml#L351-L355

perhaps also this one

https://github.com/keycloak/keycloak-quickstarts/blob/8129f103f7304497884fa9314f3db4d4d8b7695a/app-profile-jee-vanilla/src/test/resources/standalone-test.xml#L32

The same applies to `standalone-test.xml` in app-profile-saml-jee-jsp

**Comment by ahus1** [comment]
Thanks @hmlnarik - I've restructured the two tests to no longer include a custom standalone.xml. Some stabilization was necessary on the Graphene/pantomJS side of things.

The two tests were green locally. Waiting for the build to complete, switching it to draft until I have the results.

**Comment by ahus1** [comment]
This is now ready for review, there is only on failing test "extend-account-console" and this is unrelated to the bug that this PR is about to fix. 

@pedroigor / @abstractj / @vmuzikar - I'd be happy if one of you could review it, and then merge it. Thanks!

**Review by hmlnarik — APPROVED** [review]
LGTM, thanks @ahus1 !

The failure in extend-account-console test is unrelated to the "Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter" message which is indeed fixed by this PR.

**Pull request merged**
