### PR TITLE
KEYCLOAK-13623 Wrong port in user-storage-jpa quickstart

### PR DESCRIPTION
**Pull request by mabartos**
JIRA: [KEYCLOAK-13623](https://issues.redhat.com/browse/KEYCLOAK-13623)

### CODE REVIEW

**Comment by mposolda** [comment]
@abstractj Do you have a chance to review this or eventually delegate review of this PR to someone? Thanks

**Comment by mabartos** [comment]
@stianst In previous commit (before squashing), there was the port set up to `9990` and Travis failed. Server on Travis runs with maven property `-Djboss.socket.binding.port-offset=100`, so I've assumed it's by default and the port should be `10090`. WDYT?

See [start-server.sh](https://github.com/keycloak/keycloak-quickstarts/blob/fdb88b663fcc6886fec9223a43bf6daa3614bca8/scripts/start-server.sh#L40) script.

**Comment by stianst** [comment]
Following the readme there's nothing to suggest that it is not running on the default port.

**Comment by abstractj** [comment]
@douglaspalmer could you please review this?

**Comment by stianst** [comment]
Closing this PR as it now includes some commits by mistake, it's also sent to the wrong branch (it should be master for development).

**Pull request closed without merging**
