### PR TITLE
Remove Angular 2 quickstart

### LINKED ISSUE #291: Angular 2 quickstart is unmaintained
### Description

The Angular 2 quickstart has not been maintained since 2017 and runs on a version of Angular that is no longer supported.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by jonkoops**
Removes the Angular 2 quickstart as it has not been maintained since 2017. Closes #291

### CODE REVIEW

**Review by abstractj — COMMENTED** [review]
@jonkoops it makes sense to me. Would make sense to provide the community another alternative, like for example a React web app?

**Review by vmuzikar — COMMENTED** [review]
+1 for replacing this with an alternative instead of removing it because it uses an out-dated framework. ;)

**Review by edewit — DISMISSED** [review]

**Comment by vmuzikar** [comment]
@jonkoops The main (and possibly only) benefit of this QS is its visibility. The QS are an official resource linked from the KC website, packaged with every KC and even RH-SSO(!) release, so I'd be careful with removing it.

@stianst Can you please confirm removing the Angular example is ok even from the RH-SSO standpoint?

**Comment by vmuzikar** [comment]
@jonkoops Oh, I noticed this PR is going to the `latest` brach instead of `main`. Can you please re-create it?

**Comment by jonkoops** [comment]
@vmuzikar if you reopen the PR I believe I can change the target instead of re-opening a new one.

**Comment by jonkoops** [comment]
Also you might want to set `main` as the default branch if that is the place where development happens (not sure what the difference is between `latest` and `main).

**Comment by vmuzikar** [comment]
@jonkoops I'm not sure if it's possible to change the target but let's give it a try. :)

I agree the branches might a bit confusing. IMHO `latest` needs to remain the default. This repo is meant to be cloned by KC users (not contributor) and as such they should get the revision that corresponds with the latest KC released, not the dev branch. For more on this please see the [contribution guide](https://github.com/keycloak/keycloak-quickstarts/blob/latest/CONTRIBUTING.md#picking-correct-branch-for-your-pr).

**Comment by vmuzikar** [comment]
@jonkoops It actually [is possible](https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/) to change a PR target. Never noticed it during the years. :)

**Review by stianst — APPROVED** [review]

**Pull request merged**
