### PR TITLE
[KEYCLOAK-12434] - Update quickstarts with information about the uplo…

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by stianst** [comment]
Can we change the QuickStarts instead? It's not good that we have QuickStarts relying on a deprecated feature (that also is not recommended)

**Comment by pedroigor** [comment]
Yes, it is possible. I'll review wherever policies are being uploaded and update to deploy scripts instead.

**Comment by pedroigor** [comment]
@stianst done

**Comment by stianst** [comment]
Thanks

**Comment by pedroigor** [comment]
@stianst I must agree ... The addition of the script deployment is quite easy.

**Comment by slaskawi** [comment]
@pedroigor This Pull Request should be rebased on top of mine to make sure it fixes all failures: https://github.com/keycloak/keycloak-quickstarts/pull/166

In my PR, I temporarily added a flag for running the server. However, your approach is better.

**Comment by pedroigor** [comment]
@slaskawi rebased

**Comment by pedroigor** [comment]
@slaskawi Travis seems to be happy now after rebasing on top of your PR.

**Comment by pedroigor** [comment]
@slaskawi It should also fix https://issues.redhat.com/browse/KEYCLOAK-13052. Which is also updated to deploy scripts to the server.

If everything is OK I'm going to also change the `app-authz-uma-photoz`.

**Pull request merged**
