### PR TITLE
Adding keycloak-model-legacy as a dependency

### PR DESCRIPTION
**Pull request by ahus1**
Relates to keycloak/keycloak#10279

Will be merged once the main PR has been approved and merged.

### CODE REVIEW

**Comment by ahus1** [comment]
@hmlnarik - I'll keep this in draft mode until the depending PR has been merged. Locally the two modified quickstarts "keycloak-user-storage-properties" and "keycloak-user-storage-jpa-legacy" work now. 

While imitating the pattern of other quickstarts, I placed a MANIFEST.MF in the Arquillian test, still it feel strange that a developer wouldn't see this as part of the regular source. 

PropertyFileUserStorageProvider had to be extended by a new method, and AFAIK it doesn't make sense to have a default implementation here, developers need to choose between legacy and map storage here. 

Please let me know what you think of this PR. Thanks!

**Review by hmlnarik — APPROVED** [review]
This looks good to me, thank you!

**Comment by ahus1** [comment]
Updated PR to reflect latest class name changes around `SubjectCredentialManager`.

**Review by hmlnarik — APPROVED** [review]
Thank you for the fix!

**Pull request merged**
