### PR TITLE
[KEYCLOAK-5731] Error in Quickstarts tests: Could not create new inst…

### PR DESCRIPTION
**Pull request by sebastienblanc**
…ance of class EventTestRunnerAdaptor

@abstractj cherry picked your commit for Master as well

### CODE REVIEW

**Comment by abstractj** [comment]
@sebastienblanc thank you. I believe we can close this PR, because it was already merged here https://github.com/keycloak/keycloak-quickstarts/commit/d5d780dbb75db0602f67b29b5d09a575d2b6a16c ?

**Comment by sebastienblanc** [comment]
@abstractj But we need this in `master` as well, as soon 3.4.1 will be released, `master` will become `latest` or did I got confused again :) ?

**Comment by abstractj** [comment]
@sebastienblanc my PR went to `latest`. I believe your original intention with this PR is to send it to `master` not `latest`. Am I wrong?

**Comment by sebastienblanc** [comment]
Oh boy , I must stop doing PR that early ;) let me try again

**Pull request closed without merging**
