### PR TITLE
Fix compile issues with event-store-mem example

### LINKED ISSUE #327: On latest, the module event-store-mem doesn't compile any more
### Describe the bug

The API change has been introduced in this issue: 
https://github.com/keycloak/keycloak/issues/11189

### Version

999-SNAPSHOT

### PR DESCRIPTION
**Pull request by ahus1**
Closes #327

### CODE REVIEW

**Comment by ahus1** [comment]
With this change in place, `event-store-mem` is no longer on the list of failed examples. 

Other examples still fail, and will be fixed in other PRs.

@mhajas - as you've been involved in the original PR that included that API change, I ask you to review this PR. Thanks!

**Review by vmuzikar — APPROVED** [review]
@ahus1 LGTM. Thank you for your effort to make QS CI green again! 🙂

**Comment by vmuzikar** [comment]
One thing I was wondering about. With this QS broken, does it mean we did some breaking changes to our SPI? Was that intended?

**Comment by ahus1** [comment]
Hi @vmuzikar - at first sight this is a private SPI, so we're ok to change it. 

I asked @mhajas for a review here, he might add additional insights.

**Review by mhajas — APPROVED** [review]
> > One thing I was wondering about. With this QS broken, does it mean we did some breaking changes to our SPI? Was that intended?

> Hi @vmuzikar - at first sight this is a private SPI, so we're ok to change it.

Just a small addition, there are two interfaces for events - `EventListenerProvider` and `EventStoreProvider`. The first one is to listen to events, this is implemented when somebody wants to listen to events. The latter is just for events management in the Admin console. What changed are only methods from the latter, hence we most probably didn't break any existing community code because I would say people are more interested in listening to the events than replacing the store that is used for displaying the events in the Admin console.

**Comment by ahus1** [comment]
@mhajas - no worries. Getting this merged is one step to get the job back in the green, and then we'll no longer miss anything that might break.

**Pull request merged**
