### PR TITLE
KEYCLOAK-16154 Migrate QuickStarts to GitHub Actions

### PR DESCRIPTION
**Pull request by vmuzikar**
I've also sneaked in one tiny fix  for `user-storage-simple` tests.

Evidence of a running job: https://github.com/abstractj/keycloak-quickstarts/actions/runs/498430706

### CODE REVIEW

**Comment by vmuzikar** [comment]
One thing do discuss. Do we want to backport this to `latest` branch? Or will we wait for next release?

**Comment by vmuzikar** [comment]
Also we probably have to activate GitHub Actions on this repo somehow. The actions don't seem to be triggered by this PR for some reason.

**Comment by abstractj** [comment]
> Also we probably have to activate GitHub Actions on this repo somehow. The actions don't seem to be triggered by this PR for some reason.

GitHub Actions is activated once the PR is merged. But to test the changes you submitted I will give it a try at my fork.

**Comment by abstractj** [comment]
> One thing do discuss. Do we want to backport this to `latest` branch? Or will we wait for next release?

Certainly we already discussed this, but please job my poor memory. What is the point of having the latest branch?

**Comment by abstractj** [comment]
@hmlnarik would you like to review?

**Review by abstractj — APPROVED** [review]
@vmuzikar changes look good to me. One thing that's not part of the scope for your change, is the usage of the Keycloak server images, instead of building it from scratch. 

We already do that for the Node.js adapter, but I have no clue about the complexity for the Quickstarts.

**Comment by vmuzikar** [comment]
@abstractj Thanks for the review!

> GitHub Actions is activated once the PR is merged. But to test the changes you submitted I will give it a try at my fork.

Thanks but no need for that. :) I was testing it during development in my fork where it works (well, worked – since yesterday some tests hangs on some PhantomJS error, not sure yet why but might be out of scope of this PR).

> Certainly we already discussed this, but please jog my poor memory. What is the point of having the latest branch?

I don't see much sense in that branch myself. :) But please see [CONTRIBUTING.MD](https://github.com/keycloak/keycloak-quickstarts/blob/latest/CONTRIBUTING.md#picking-correct-branch-for-your-pr).

> One thing that's not part of the scope for your change, is the usage of the Keycloak server images, instead of building it from scratch.

That was my original intention too but then I realized there are two problems with that:
1. In `master` branch we really need to test against latest Keycloak master to find possible issues caused by Keycloak as soon as possible. At least this was my understanding, please correct me if I'm wrong. ;)
2. We need to deploy an extension to the Keycloak dist – the JS policies. If I understand it correctly, [it is not exactly straightforward](https://github.com/keycloak/keycloak-containers/blob/master/server/README.md#adding-a-custom-provider) in case of the Docker image. Using the ZIP dist seemed to me like a much easier solution.

**Comment by vmuzikar** [comment]
I fixed the intermittent events tests failures by switching to Chrome. PhantomJS doesn't support the old Admin Console anymore which apparently caused it to hang. The tests are of course still failing but at least they finish.

I haven't yet squashed the changes to make them more visible.

**Comment by vmuzikar** [comment]
@abstractj What can we do to get this merged? :) Do we need @hmlnarik review?

**Review by mhajas — APPROVED** [review]
Thanks @vmuzikar. LGTM, there are some failures, but it is expected. It will be fixed by other PRs

**Comment by vmuzikar** [comment]
@mhajas Pushed (hopefully) one last change fixing authz spring security tests.

**Review by mhajas — APPROVED** [review]

**Comment by vmuzikar** [comment]
I've created a [separate branch](https://github.com/vmuzikar/keycloak-quickstarts/tree/gh-actions_TEST) which contains all QS fixes, even the unmerged ones. [Here](https://github.com/vmuzikar/keycloak-quickstarts/actions/runs/733497788) you can find a successful GH Actions run.

**Review by abstractj — APPROVED** [review]

**Pull request merged**
