### PR TITLE
KEYCLOAK-5169 : Bump to 3.2.0.Final 

### PR DESCRIPTION
**Pull request by sebastienblanc**
@abstractj Does this look okay for you ?

### CODE REVIEW

**Comment by abstractj** [comment]
@sebastienblanc is this PR a merge from `master` to `latest`?

**Comment by sebastienblanc** [comment]
It's a rebase of `latest` from `master` + a commit to set the version to `3.2.0.Final`

**Comment by sebastienblanc** [comment]
And Travis is finally happy

**Comment by abstractj** [comment]
@sebastienblanc it looks good, but I feel like I'm doing something wrong. I'm getting the following error: 

```
org.jboss.as.controller.client.helpers.standalone.ServerDeploymentHelper$ServerDeploymentException: java.lang.Exception: "WFLYCTL0216: Management resource '[(\"deployment\" => \"test-demo.war\")]' not found"
```
What I did was:

1. Setup Keycloak 3.2.0.Final with user `admin`, password `admin` and start it on port 8180
2. mvn clean install -Pwildfly-managed -Denforcer.skip=true at the main folder.

**Comment by sebastienblanc** [comment]
Just tried with a fresh clone and new KC 3.2.0.Final , I can not reproduce your issue.

**Comment by abstractj** [comment]
@sebastienblanc so go ahead, you and Travis can't be wrong

**Pull request merged**
