### PR TITLE
[app-springboot] Correct server port in readme

### PR DESCRIPTION
**Pull request by ThomasVitale**

### CODE REVIEW

**Comment by abstractj** [comment]
@ThomasVitale thank you, I believe it was landed here https://github.com/keycloak/keycloak-quickstarts/commit/3b660ff6464643d99068e49c4c9ab074c75199b0.

@sebastienblanc I'm closing this, because looks like you already merged.

Feel free to reopen if I'm wrong.

**Comment by abstractj** [comment]
Ignore my previous comments, I just overlooked it.

@sebastienblanc I believe we're good to go.

**Comment by ThomasVitale** [comment]
Hi @abstractj, this change is not the same as [3b660ff](https://github.com/keycloak/keycloak-quickstarts/commit/3b660ff6464643d99068e49c4c9ab074c75199b0), it's in a different file

**Comment by ThomasVitale** [comment]
Ok, thanks

**Pull request merged**
