### PR TITLE
[KEYCLOAK-11282] - Spring Boot Multi-tenancy Quickstart

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by mhajas — DISMISSED** [review]
Thanks @pedroigor, great work! It works as expected with changes from https://github.com/keycloak/keycloak/pull/6898

**Comment by pedroigor** [comment]
@stianst @mhajas It seems that only a subset of spring quickstarts tests is running in CI, is that right?

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@pedroigor Could you please rebase, so we could try to run the tests with GH Actions?

**Comment by pedroigor** [comment]
@vmuzikar There we go. Rebased and tests running fine locally.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@pedroigor Thanks! That was fast. :)

Could you please add the tests to [GH Actions](https://github.com/keycloak/keycloak-quickstarts/blob/master/.github/scripts/run-tests.sh)?

**Comment by pedroigor** [comment]
@vmuzikar Done. Going to cancel the previous build.

**Review by vmuzikar — APPROVED** [review]
@pedroigor Thanks!

The tests failed but on some unrelated QS (action-token-required-action) and some weird random error:
```
[ERROR] Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.2.2.Final:execute-commands (add-spi-configurations) on project provider-action-token-required-action: Execution add-spi-configurations of goal org.wildfly.plugins:wildfly-maven-plugin:1.2.2.Final:execute-commands failed: Command execution failed for command ':reload'. Communication error: java.util.concurrent.CancellationException: Operation was cancelled
```
I'd re-run the checks but I don't have the permissions. But given it was unrelated failure, I'm approving this (based on @mhajas review). I think we're good to go.

**Review by vmuzikar — CHANGES_REQUESTED** [review]
On the other hand, the log is completely swamped with htmlunit errors `DefaultCssErrorHandler` which is weird and makes it hard to read. Any idea what's causing it?

**Comment by vmuzikar** [comment]
@pedroigor Could you  please rebase? The GH Actions issues should be resolved now.

Regarding the swamped log with htmlunit warnings. It seems like it doesn't like one of the CSS. IMHO we could easily switch to chromeheadless to solve the problem. Just don't forget to add `pageLoadTimeout(30, TimeUnit.SECONDS)`, similarly to e.g. [here](https://github.com/keycloak/keycloak-quickstarts/blob/cdb5bc08af63e84d5c39d503154e08fadbbbfa54/app-jee-html5/src/test/java/org/keycloak/quickstart/ArquillianJeeHtml5Test.java#L118).

**Comment by pedroigor** [comment]
@vmuzikar We don't use arquillian in this quickstart.

**Comment by vmuzikar** [comment]
@pedroigor Ah, right. Ok, so maybe we could then use `webClient.setCssErrorHandler(new SilentCssErrorHandler());`? This should get rid of the trillion warn messages in the log. :) I'd really like to have the log without the messages. It's then soooo big than it even doesn't display in the GH Actions log.

**Comment by pedroigor** [comment]
@vmuzikar Done. Thanks for the tip.

**Review by abstractj — APPROVED** [review]

**Pull request merged**
