### PR TITLE
KEYCLOAK-13055 Fix flow setup in action-token-authenticator test

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Comment by hmlnarik** [comment]
Thanks @slaskawi for review! For demonstration purposes, I've rebased this in #170.

**Comment by slaskawi** [comment]
@hmlnarik Perfect! Thank you!

**Comment by hmlnarik** [comment]
group2 finished green in #170. I believe this is ready to be merged. Thanks @slaskawi for the hint!

**Comment by hmlnarik** [comment]
Rebased to latest master.

**Pull request merged**
