### PR TITLE
[KEYCLOAK-6543] Make the photoz example a quickstart.

### PR DESCRIPTION
**Pull request by sguilhen**
We need to port the missing examples as quickstarts so that the authz examples in Keycloak can be deleted.

### CODE REVIEW

**Comment by pedroigor** [comment]
@abstractj, can we have this one in ? Upstream changes already merged.

**Comment by sguilhen** [comment]
@abstractj working on it, thanks for the review

**Comment by pedroigor** [comment]
@abstractj, The tests now are implemented and I have successfully run them after Stefan's latest changes to this PR.

However, I think Travis won't be able to run these tests in particular because they need either FF or Chrome. Pretty much the same "problem" we have in upstream, where some tests don't work with phamtonjs and are not run in Travis.

What do you think ? Can we start merging this one ?

**Comment by pedroigor** [comment]
@abstractj, OK. Will check if Stefan can do that. Otherwise I'll send another PR with his changes + the one you requested.

**Comment by pedroigor** [comment]
Closed in favor of https://github.com/keycloak/keycloak-quickstarts/pull/104.

**Pull request closed without merging**
