### PR TITLE
[KEYCLOAK-13856] Update quickstarts from Wildfly 14 to Wildfly 19.

### PR DESCRIPTION
**Pull request by douglaspalmer**

### CODE REVIEW

**Comment by abstractj** [comment]
@douglaspalmer I believe we need to investigate why Travis is failing.

**Comment by abstractj** [comment]
@douglaspalmer @pskopek we need to take some action on this or close the issue if we don't plan to work on it anymore.

**Comment by douglaspalmer** [comment]
> @douglaspalmer @pskopek we need to take some action on this or close the issue if we don't plan to work on it anymore.

We already established that the failures weren't related to the changes. I'm not sure why it never got merged. It looks like it needs rebasing now. Given that Keycloak is now on Wildfly 20 maybe it's better to close this and open a Jira to upgrade to Wildfly 20?

**Comment by douglaspalmer** [comment]
> > @douglaspalmer @pskopek we need to take some action on this or close the issue if we don't plan to work on it anymore.
> 
> We already established that the failures weren't related to the changes. I'm not sure why it never got merged. It looks like it needs rebasing now.

Rebased

**Review by martin-kanis — APPROVED** [review]

**Comment by abstractj** [comment]
@douglaspalmer I understand what you say, but fix the issues in the CI should be also our concern. Merging it for now.

**Pull request merged**
