### PR TITLE
KEYCLOAK-5949 : update current repo instead of adding new one

### PR DESCRIPTION
**Pull request by sebastienblanc**
@vramik : this should do the trick, wdyt ?

### CODE REVIEW

**Comment by vramik** [comment]
@sebastienblanc it seems so, yeah. How often is https://github.com/redhat-developer/redhat-sso-quickstarts/blob/7.2.x-devel actually updated. Right now there is still old version of the pom.xml

**Comment by sebastienblanc** [comment]
@vramik each time that something is merged to master in the community quickstarts it should push to the redhat-dev repo as well.

**Comment by sebastienblanc** [comment]
@vramik Maybe let's just merge this and see if it's okay what is pushed ?

**Comment by vramik** [comment]
@sebastienblanc agreed

**Comment by abstractj** [comment]
@sebastienblanc @stianst did some changes to the productize.sh script. Please, make sure that you rebased against these changes.

**Comment by stianst** [comment]
I'm closing this as the productize.sh script now removes the old repositories block before adding a new one. So this issue has been resolved.

**Pull request closed without merging**
