### PR TITLE
adding app-vue application

### PR DESCRIPTION
**Pull request by akoserwal**
Guide: 
https://github.com/keycloak/keycloak-web/pull/139

### CODE REVIEW

**Comment by akoserwal** [comment]
@stianst please review & let me know your thoughts.

**Comment by stianst** [comment]
@ssilvert @edewit can you please take a look at this? It is the start of extending Getting Started section on keycloak.org to also cover simple guides for different application types.

**Review by edewit — CHANGES_REQUESTED** [review]
Wouldn't it be nice to include a `Readme.md` with steps how to install and run?

**Comment by edewit** [comment]
wait I see that is done in https://github.com/keycloak/keycloak-web/pull/139

**Review by edewit — APPROVED** [review]

**Comment by TheArKaID** [comment]
Why this application/vue doesn't exist in the latest keycloak-quickstarts ? The [Keycloak - Guide - Vue.js](https://www.keycloak.org/securing-apps/vue#_code_repository) said that application/vue is available.

**Comment by J3m5** [comment]
Hi,
Same as @TheArKaID , I came here to look at the vue example feom the docs.

**Comment by TheArKaID** [comment]
> 
> 
> Hi,
> Same as @TheArKaID , I came here to look at the vue example from the docs.

I don't know when it's gone, but u could check the vue example here @J3m5 [akoserwal/keycloak-quickstart](https://github.com/akoserwal/keycloak-quickstarts/tree/sec-getting-started-apps/applications/app-vue)

**Comment by stratosgear** [comment]
I am also surprised the Vue app is missing here. I see the MR as merged but the submitted files are nowhere to be found.  Curious to know why they were removed!!

**Comment by irgeek** [comment]
@akoserwal @stianst @edewit @ssilvert 

Sorry to @ everyone, but issues are disabled in this repo so there's no other way to get visibility when reporting a problem.

It looks like your `keycloak-bot` has been misbehaving since about `6.0.1`. If you look a the 12.0.x commits, for instance, 12.0.0 is the direct parent commit of 12.0.1, which is the direct parent of 12.0.2, which is the direct parent of 12.0.3, which is the direct parent of 12.0.4. Looking at a diff between [12.0.0 and 12.0.4](https://github.com/keycloak/keycloak-quickstarts/compare/keycloak:12.0.0...12.0.4) you can see that there are zero code changes -- just the version bump from 12.0.0 to 12.0.4 in 50 files.

As for this PR, the [original commit](https://github.com/akoserwal/keycloak-quickstarts/commits/sec-getting-started-apps) in the source repository was based on the commit tagged `11.0.1` so I'm guessing it was removed somehow when `keycloak-bot` created the next version tag.

I haven't managed to work out if this is the only commit that's been lost. It might be worth auditing the PRs and making sure all of them have survived in the current code base.

**Comment by edewit** [comment]
@irgeek issues can be logged on https://issues.redhat.com/projects/KEYCLOAK/ as described here: https://github.com/keycloak/keycloak#reporting-an-issue

**Comment by vmuzikar** [comment]
@irgeek I believe the `keycloak-bot` is not misbehaving. The `latest` branch is meant to be a "snapshot" of the latest released version, it's not the upstream branch where the development happens. Please see the [contribution guide](https://github.com/keycloak/keycloak-quickstarts/blob/master/CONTRIBUTING.md#picking-correct-branch-for-your-pr). Sometimes there are no changes between releases but we keep the Quickstarts version in sync with Keycloak server. That's why there are sometimes no code changes, just a version bump.

What happened here was that this PR was created in a wrong branch (`latest` instead of `master`) and therefore the changes got overwritten with a release.

@akoserwal I know this is an old PR but could I ask you to rebase your changes from this PR and create a new one in the `master` branch?

**Comment by vmuzikar** [comment]
Restored the QS here: https://github.com/keycloak/keycloak-quickstarts/pull/248

**Pull request merged**
