### PR TITLE
Adds a new quickstart for AuthZ and SpringBoot REST

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by pedroigor** [comment]
@abstractj, shall we update poms to 3.4.0.CR1-SNAPSHOT in master ?

**Comment by abstractj** [comment]
@pedroigor that would be nice +1

**Comment by pedroigor** [comment]
@abstractj, I've updated poms with latest version from upstream and enabled test execution for the new quickstart.

Tavis is failing and it seems the tests in failure are unrelated with my changes. But related with ```app-angular2```. Do you have any clue what may be causing this ?

**Comment by abstractj** [comment]
@pedroigor I'm closing it, see https://github.com/keycloak/keycloak-quickstarts/pull/55

**Pull request closed without merging**
