### PR TITLE
[KEYCLOAK-4253] Functional tests for quickstarts

### PR DESCRIPTION
**Pull request by abstractj**
@vramik @sebastienblanc could you please review?

Instructions to review this PR:

1. First you must build this PR https://github.com/keycloak/keycloak/pull/4003
```
git clone https://github.com/abstractj/keycloak.git && cd keycloak && git checkout refactor-test-helper
mvn clean install -Pdistribution -DskipTests=true
```
2. And after that start Keycloak server: 
```
bin/standalone.sh -b 0.0.0.0 -Djboss.socket.binding.port-offset=100
```
3. Run the tests
```
mvn clean install -Pwildfly-managed -Denforcer.skip=true
```
Note: I'm working on issues with Travis CI

### Travis CI

After the merge of this PR and Keycloak release, is possible to remove the `git clone` on Travis and Keycloak local build.

### CODE REVIEW

**Comment by vramik** [comment]
Hi @abstractj,
I've tried the PR and I have some difficulties with it. My steps:
1. cherry-pick https://github.com/keycloak/keycloak/pull/4003
2. build keycloak
3. start server with `bin/standalone.sh -b 0.0.0.0 -Djboss.socket.binding.port-offset=100`
4. to be able to compile the project I had to add 
```
<dependency>
    <groupId>org.keycloak</groupId>
    <artifactId>keycloak-test-helper</artifactId>
    <scope>compile</scope>
    <version>${project.version}</version>
</dependency>
```
to parent pom.
5. run the tests `mvn clean install -Pwildfly-managed -Denforcer.skip=true`
6. there is output: http://pastebin.test.redhat.com/472107

**Comment by abstractj** [comment]
@vramik I just updated the PR instructions. But I believe these are the missing steps:

```
git clone https://github.com/abstractj/keycloak.git && cd keycloak && git checkout refactor-test-helper
mvn clean install -Pdistribution -DskipTests=true
```
Just let me know how it goes.

**Comment by vramik** [comment]
@abstractj still the same result: https://keycloak-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Playground/job/test-qs/3/console

**Comment by sebastienblanc** [comment]
Tests are passing for me

**Comment by abstractj** [comment]
@vramik ^^^

**Comment by sebastienblanc** [comment]
@vramik Could it be related to the JVM version you are using ?

**Comment by vramik** [comment]
@sebastienblanc I don't know, locally I use OpenJDK (build 1.8.0_121-b14), in CI there is Oracle (build 1.8.0_111-b14). What are you using?

**Comment by sebastienblanc** [comment]
@vramik Indeed, I'm using the same as you `java-1.8.0-openjdk-1.8.0.121-8.b14.fc24.x86_64`

**Comment by sebastienblanc** [comment]
@vramik Okay, I just checked your logs again and I think this is the issue : 
`07:56:12,000 WARN  [org.keycloak.events] (default task-1) type=LOGIN_ERROR, realmId=master, clientId=admin-cli, userId=null, ipAddress=127.0.0.1, error=invalid_user_credentials, auth_method=openid-connect, grant_type=password, client_auth_method=client-secret, username=admin` 
Do you have an admin/admin user on the master realm ?

**Comment by vramik** [comment]
Thanks @sebastienblanc, that is the cause. I've followed blindly the instructions and there is no info about the user, but it is logical that the user should be created, sorry.

**Comment by sebastienblanc** [comment]
@vramik In the top level of the repo we have some instructions about adding an admin user (https://github.com/abstractj/keycloak-quickstarts/tree/KEYCLOAK-4253#add-admin-user) but maybe we should make it more clear that for the running the tests by default it should be `admin/admin` , @abstractj wdyt ?

**Comment by vramik** [comment]
@sebastienblanc `admin/admin` is required? Or any "admin"? If `admin\admin` I think it should be mentioned. BTW for tests I've used https://github.com/keycloak/keycloak/blob/master/testsuite/integration-arquillian/tests/base/src/test/resources/keycloak-add-user.json

**Comment by sebastienblanc** [comment]
@vramik By default in the test class an admin user with user name `admin` and `password` is required https://github.com/keycloak/keycloak-quickstarts/blob/master/service-jee-jaxrs/src/test/java/org/keycloak/quickstart/jaxrs/ArquillianTest.java#L48 but the developer can easily change this. But I agree that we should maybe be more explicit.

**Comment by abstractj** [comment]
@sebastienblanc I believe we just need to change the tests to use test-admin, nope? We agreed on that, as far as I recall. See: https://github.com/keycloak/keycloak-quickstarts/pull/12/files#diff-d779962a6aa8c61dcf892fd7c5c9674dR31

@vramik ^^^

**Comment by sebastienblanc** [comment]
@abstractj Yes I remember we discussed that but I'm confused again :)  The  `test-admin` user is inside the `quickstart-realm` that we need to import first with an admin user from the 'master' realm . 
Additionaly, If we use the `start-server.sh` you provided under the `scripts` folder, an `admin/admin` will be created in the master realm.

**Comment by sebastienblanc** [comment]
Maybe this is enough ? https://github.com/abstractj/keycloak-quickstarts/pull/2

**Comment by vramik** [comment]
@sebastienblanc I believe it is sufficient, I wanted to add https://github.com/keycloak/keycloak-quickstarts/pull/14 to be able to use it in CI (automatically create `admin\admin`). By default it is not used. But I can also add the user by `bin/add-user-keycloak.sh -u admin -p admin` so maybe https://github.com/keycloak/keycloak-quickstarts/pull/14 is not necessary to have

**Comment by sebastienblanc** [comment]
@vramik yes, for your CI job if think `bin/add-user-keycloak.sh -u admin -p` is enough

**Comment by abstractj** [comment]
@vramik +1 for "_add the user by bin/add-user-keycloak.sh -u admin -p admin_". I will close that PR and update the README instructions

**Comment by sebastienblanc** [comment]
@abstractj Already did the PR to update the readme ;) https://github.com/abstractj/keycloak-quickstarts/pull/2

**Comment by abstractj** [comment]
@sebastienblanc @vramik I believe we're good to merge now, right? @sebastienblanc I just update your readme instructions, let me know if there are any dirty grammar errors.

**Comment by sebastienblanc** [comment]
It's all good, let me merge it

**Pull request merged**
