### PR TITLE
KEYCLOAK-5535 - Edited config location in readme

### PR DESCRIPTION
**Pull request by Pepo48**

### CODE REVIEW

**Comment by abstractj** [comment]
@Pepo48 I'm not if it's really necessary, because today Maven plugin is copying it here https://github.com/keycloak/keycloak-quickstarts/blob/latest/app-jee-html5/pom.xml#L92-L108 to the proper place.

**Comment by Pepo48** [comment]
Originally, @zschwarz has reviewed this QS 2 or 3 months ago and I also remember that we have had to manually copy file to the webapp directory, to be able to compile it successfully. 
Anyway, it seems like I will have to review whole QS again, to provide you some more details for JIRA issue, so we would close this after that.

**Comment by abstractj** [comment]
@Pepo48 np, take your time and let me know if I can help.

**Comment by abstractj** [comment]
Superseded by https://github.com/keycloak/keycloak-quickstarts/pull/91

**Pull request closed without merging**
